#!/bin/bash
#
# M9-5 (#120): after the HOST reboots into hype.efi again, does an ALREADY-INSTALLED guest disk
# still boot -- not just a fresh installer?
#
#   tools/120/run-installed-disk-host-reboot.sh [seconds]
#
# Every other QEMU rig in this repo boots a guest from installer MEDIA. That leaves the case M9-5
# is about untested: a VM whose OS lives on its own disk, brought up by the guest firmware's own
# boot path, across a host power event.
#
# THE INSTALLED DISK IS BUILT, NOT INSTALLED, and that is #262's precedent rather than a shortcut.
# A real install needs either a physical target or a multi-minute unattended installer, and neither
# adds anything to the question being asked: what has to work is that the guest firmware finds and
# runs \EFI\BOOT\BOOTX64.EFI on the guest's OWN GPT disk with no media attached. The payload is the
# UEFI Shell because it says WHICH device it booted from -- `Shell>` plus a mapping table naming
# the device path -- so a pass names the disk instead of being inferred from the absence of a BDS
# failure message. What this does NOT cover is a kernel and a root filesystem; that belongs to a
# real install (#228) and is called out in the report rather than implied by a green line here.
#
# THE CONTROL RUNS FIRST, also #262's lesson: bare QEMU must boot the generated image over SATA
# before hype is ever given it. Without that, "hype's disk model refused it" and "the image was
# never bootable" look identical -- and that ticket spent three hypotheses before the control
# existed.
#
# THE HOST REBOOT uses the build-time trigger #175 added for its own validation, because the
# `host reboot` verb needs a physical keyboard. The script builds that binary itself and REFUSES to
# run if the flag did not reach the compiler: a run that never reboots would still show the guest
# booting from disk once, and would pass for the wrong reason.
#
set -u
. "$(git rev-parse --show-toplevel)/tools/qemu-env.sh"
export LC_ALL=C
cd "$(git rev-parse --show-toplevel)"
REPO=$PWD

SECS="${1:-200}"
REBOOT_AT="${REBOOT_AT:-70}"
# rig/, never build/: `make clean` is `rm -rf build/`, and it has already destroyed a rig once.
# Everything in here is regenerated by this script on every run, so losing it costs only time --
# but the rule is the rule, and a future rig that is NOT regenerable would inherit the wrong path.
S="${SCRATCH:-rig/120}"
OVMF_CODE="${OVMF_CODE:-/usr/share/edk2/ovmf/OVMF_CODE.fd}"
OVMF_VARS="${OVMF_VARS:-/usr/share/edk2/ovmf/OVMF_VARS.fd}"
SHELL_ISO="${SHELL_ISO:-/usr/share/edk2/ovmf/UefiShell.iso}"

mkdir -p "$S"
for f in "$OVMF_CODE" "$OVMF_VARS" "$SHELL_ISO"; do
    [ -f "$f" ] || { echo "missing $f"; exit 2; }
done

echo "=== building hype with the #175 host-reboot trigger at ${REBOOT_AT}s ==="
rm -f build/boot/main.o
make all EXTRA_CFLAGS="-DHYPE_175_AUTOTEST_SECS=$REBOOT_AT" 2>&1 | tee "$S/build.log" | tail -2
grep -q "HYPE_175_AUTOTEST_SECS=$REBOOT_AT" "$S/build.log" || {
    echo "FAILED: the reboot trigger did not reach the compiler -- this run could not reboot the"
    echo "host and would pass for the wrong reason. Refusing to run."
    exit 2
}

cd "$S"

# ------------------------------------------------------- the installed guest disk
if [ ! -f BOOTX64.EFI ]; then
    rm -rf shelliso && mkdir shelliso && (cd shelliso && 7z x -y "$SHELL_ISO" >/dev/null)
    mcopy -i shelliso/uefi_shell.img ::/EFI/BOOT/BOOTX64.EFI ./BOOTX64.EFI
fi
# GPT + one FAT32 ESP + the removable-media fallback path, which is what BDS looks for with no
# NVRAM boot entry. Fully allocated, never sparse: hype's file-backed writer never grows a file, so
# a hole is not "unwritten" and a host FS asked to allocate on first write to one would fail the
# guest's write mid-run (same reasoning as tools/make-disk-image.sh).
rm -f installed.img esp.fat
dd if=/dev/zero of=installed.img bs=1M count=128 status=none
sfdisk --label gpt installed.img >/dev/null <<'PART'
start=2048, size=253952, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, name="EFI System"
PART
dd if=/dev/zero of=esp.fat bs=512 count=253952 status=none
mformat -i esp.fat -F -v HYPEBOOT ::
mmd -i esp.fat ::/EFI ::/EFI/BOOT
mcopy -i esp.fat BOOTX64.EFI ::/EFI/BOOT/BOOTX64.EFI
dd if=esp.fat of=installed.img bs=512 seek=2048 conv=notrunc status=none

# ------------------------------------------------------------------- THE CONTROL
echo "=== control: bare QEMU must boot installed.img over SATA ==="
cp "$OVMF_VARS" ctrl-vars.fd
rm -f ctrl.log
timeout 90 "$QEMU" -machine q35 -m 2048 -nodefaults -accel kvm -cpu host \
  -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE" \
  -drive if=pflash,format=raw,file=ctrl-vars.fd \
  -drive format=raw,file=installed.img,if=none,id=d0 -device ide-hd,drive=d0,bus=ide.0 \
  -serial file:ctrl.log -display none >/dev/null 2>&1 || true
if grep -aq "Shell>" ctrl.log 2>/dev/null; then
    echo "   CONTROL PASS -- the disk is bootable on its own:"
    tr -d '\r' < ctrl.log | grep -ao "Sata([^)]*)/HD([^)]*)" | head -1 | sed 's/^/     /'
else
    echo "   CONTROL FAIL -- installed.img is not bootable, so nothing hype does with it would"
    echo "   mean anything. Fix the image before reading any hype result."
    exit 1
fi

# --------------------------------------------------------------- hype's own ESP
rm -f esp-hype.img esp-hype.fat
dd if=/dev/zero of=esp-hype.img bs=1M count=640 status=none
sfdisk --label gpt esp-hype.img >/dev/null <<'PART'
start=2048, size=1306624, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, name="EFI System"
PART
dd if=/dev/zero of=esp-hype.fat bs=512 count=1306624 status=none
mformat -i esp-hype.fat -F -v HYPEESP ::
mmd -i esp-hype.fat ::/EFI ::/EFI/BOOT ::/EFI/hype ::/hype ::/hype/disks
mcopy -i esp-hype.fat "$REPO/build/hype.efi" ::/EFI/BOOT/BOOTX64.EFI
mcopy -i esp-hype.fat "$REPO/fw/OVMF_CODE.fd" "$REPO/fw/OVMF_VARS.fd" ::/EFI/hype/
mcopy -i esp-hype.fat installed.img ::/hype/disks/installed.img
# No install_media at all: an installer ISO in the config would leave "did it boot the disk or the
# media?" unanswerable, which is the whole distinction M9-5 draws.
cat > hype.cfg <<'CFG'
[hype]
config_version = 1

[vm.installed]
label = already-installed disk
vcpus = 1
mem_mb = 1024
boot = disk
target_disk = file:\hype\disks\installed.img
firmware = uefi
os_hint = linux
CFG
mcopy -i esp-hype.fat hype.cfg ::/hype.cfg
dd if=esp-hype.fat of=esp-hype.img bs=512 seek=2048 conv=notrunc status=none

# ------------------------------------------------------------------------- run
# #371/#581: roughly one QEMU boot in four on this host never reaches hype at all (SIGSEGV in
# QEMU's own ahci_commit_buf(), qemu-project/qemu#437, fixed in QEMU 11.1.0 -- this host is below
# that). Such a boot is INVALID, not failed: hype was never entered, so nothing about it was under
# test. Retry it, bounded, and never score it. The first run of this script hit exactly that and
# correctly refused to report a result -- which is right, but a rig that needs a human to re-run it
# is a rig that gets read as a failure.
BOOT_ATTEMPTS="${BOOT_ATTEMPTS:-3}"
LOG=serial.txt
attempt=1
while :; do
    echo "=== booting hype for ${SECS}s (host reboots at ${REBOOT_AT}s), attempt $attempt ==="
    cp "$OVMF_VARS" VARS.fd
    rm -f "$LOG"
    # -vga std, not none: with `none` hype's display path never runs at all, which is how #370's
    # rdmsr #GP hid behind what looked like a render stall.
    timeout "$SECS" "$QEMU" \
      -machine q35 -m 4096 -nodefaults \
      -accel kvm -cpu host -smp 4 \
      -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE" \
      -drive if=pflash,format=raw,file=VARS.fd \
      -drive format=raw,file=esp-hype.img,if=none,id=esp \
      -device ide-hd,drive=esp,bus=ide.0,bootindex=0 \
      -serial file:"$LOG" -display none -vga std >/dev/null 2>&1 || true
    grep -aq '^hype: build' "$LOG" && break
    if [ "$attempt" -ge "$BOOT_ATTEMPTS" ]; then
        echo "INVALID: the firmware never launched hype in $BOOT_ATTEMPTS attempts (#371)."
        echo "  Not a hype result and must not be scored. Log: $S/$LOG"
        exit 2
    fi
    echo "  no hype banner (#371) -- retrying, attempt $((attempt + 1)) of $BOOT_ATTEMPTS"
    attempt=$((attempt + 1))
done

rc=0
boots=$(grep -ac '^hype: build' "$LOG" || true)
echo
echo "host boots (banner):        $boots"
if [ "$boots" -lt 2 ]; then
    echo "INVALID: the host did not reboot within ${SECS}s (banners=$boots) -- nothing to verify."
    echo "  Raise the timeout or lower REBOOT_AT. Not a result. Log: $S/$LOG"
    exit 2
fi

# The guest's own verdict, counted per host boot. The second banner is the line the interesting one
# has to come AFTER: booting the disk once proves the path works, booting it again after the host
# went down and came back is what M9-5 asks.
second_banner=$(grep -an '^hype: build' "$LOG" | sed -n 2p | cut -d: -f1)
shell_total=$(grep -ac 'Shell>' "$LOG" || true)
shell_after=$(awk -v n="$second_banner" 'NR>n && /Shell>/' "$LOG" | wc -l)
echo "guest reached Shell> :      $shell_total total, $shell_after after boot 2's banner (line $second_banner)"
[ "$shell_total" -ge 1 ] || { echo "FAIL: the guest never booted its installed disk at all"; rc=1; }
[ "$shell_after" -ge 1 ] || { echo "FAIL: the installed disk did not boot after the host rebooted"; rc=1; }

# Which device the guest firmware used, so a pass names the disk rather than implying it.
echo "guest boot device:"
tr -d '\r' < "$LOG" | grep -ao "Sata([^)]*)/HD([^)]*)" | sort -u | head -3 | sed 's/^/  /'

# No installer media is configured, so any media resolve would mean the guest booted something
# other than the disk under test.
if grep -aq 'install_media' "$LOG"; then
    echo "NOTE: the log mentions install_media -- check the guest booted the DISK, not media."
fi

echo
if [ "$rc" = 0 ]; then
    echo "PASS (#120): an already-installed guest disk booted after the host rebooted into hype.efi."
    echo "  Covers: guest firmware finding and running \\EFI\\BOOT\\BOOTX64.EFI on the guest's own"
    echo "  GPT disk, with no installer media attached, across a host power event."
    echo "  Does NOT cover: a real kernel + root filesystem. That needs an actual install (#228)."
else
    echo "FAIL (#120). Log: $S/$LOG"
fi
exit $rc
