#!/bin/bash
#
# M9-1 (#119): does a VM's varstore survive a HOST reboot?
#
#   tools/119/run-varstore-host-reboot.sh [seconds]
#
# #59 gave each VM an emulated flash/varstore and #441 persists it to hype's own log volume as
# \vars-<name>.bin. This asks the question M9-1 actually asks: after the HOST goes down and comes
# back, does the guest firmware find its variables again?
#
# WHY THIS RIG AND NOT tools/run-guest.sh. The varstore save and restore both go through
# g_hype_log.fs, and that only exists when hype has mounted its log volume -- which needs a USB
# mass-storage device. run-guest.sh attaches none, so on that rig every varstore call is a silent
# no-op and this test would pass by never running. That exact confusion has already produced one
# wrong conclusion on #441, so the USB stick here is not optional scenery.
#
# HOW THE HOST REBOOT HAPPENS. hype's `host reboot` verb needs a physical keyboard, so this uses
# the same build-time trigger #175 added for its own validation: -DHYPE_175_AUTOTEST_SECS=<n>
# begins a host reboot n seconds after boot, exactly as the typed command would. The script builds
# that binary itself, because a run against a binary without the gate would simply never reboot and
# would still print a "saved" line -- passing for the wrong reason.
#
# WHAT IS ACTUALLY CHECKED, and why a "restored" line alone is not enough:
#
#   1. boot 1 saves          `VARS: vars-<vm>.bin saved`
#   2. boot 2 restores       `VARS: vars-<vm>.bin restored`, and it must appear AFTER the second
#                            `hype: build` banner -- a restore is only meaningful if it happened on
#                            a later boot of the host.
#   3. the bytes DIFFER      from the pristine fw/OVMF_VARS.fd this build ships. A restore that put
#      from pristine         back the shipped file would produce exactly the same two log lines
#                            while persisting nothing, which is the "consistent with success but
#                            not a verdict" trap. If the guest firmware wrote a single variable,
#                            the saved image cannot equal the pristine one.
#
set -u
export LC_ALL=C
cd "$(git rev-parse --show-toplevel)"

SECS="${1:-160}"
REBOOT_AT="${REBOOT_AT:-55}"
# rig/, never build/: `make clean` is `rm -rf build/`, and it has already destroyed a rig once.
# Everything in here is regenerated by this script on every run, so losing it costs only time --
# but the rule is the rule, and a future rig that is NOT regenerable would inherit the wrong path.
S="${SCRATCH:-rig/119}"
OVMF_CODE="${OVMF_CODE:-/usr/share/edk2/ovmf/OVMF_CODE.fd}"
OVMF_VARS="${OVMF_VARS:-/usr/share/edk2/ovmf/OVMF_VARS.fd}"
ISO="${ISO:-disk-images/alpine-virt-3.21.7-x86_64.iso}"

# Never under /tmp: it is tmpfs here, so rig media there would both hit the quota and steal the
# RAM the guests need.
mkdir -p "$S"
[ -f "$OVMF_CODE" ] || { echo "no host OVMF at $OVMF_CODE"; exit 2; }
[ -f "$ISO" ] || { echo "no ISO at $ISO -- set ISO=<path>"; exit 2; }

echo "=== building hype with the #175 host-reboot trigger at ${REBOOT_AT}s ==="
# The flag only affects boot/main.c, and `make` does not notice a changed EXTRA_CFLAGS on its own --
# so drop that one object rather than the whole tree, and CONFIRM the flag reached the compiler.
rm -f build/boot/main.o
make all EXTRA_CFLAGS="-DHYPE_175_AUTOTEST_SECS=$REBOOT_AT" 2>&1 | tee "$S/build.log" | tail -2
grep -q "HYPE_175_AUTOTEST_SECS=$REBOOT_AT" "$S/build.log" || {
    echo "FAILED: the reboot trigger did not reach the compiler -- this run could not reboot the"
    echo "host and would pass for the wrong reason. Refusing to run."
    exit 2
}

echo "=== staging media ==="
rm -f "$S/usb.img" "$S/esp.img" "$S/VARS.fd"
# 512 MB so the ISO fits beside the firmware images.
dd if=/dev/zero of="$S/esp.img" bs=1M count=512 status=none
mkfs.vfat -F 32 -n HYPEESP "$S/esp.img" >/dev/null
mmd -i "$S/esp.img" ::/EFI ::/EFI/BOOT ::/EFI/hype ::/iso
mcopy -i "$S/esp.img" build/hype.efi ::/EFI/BOOT/BOOTX64.EFI
mcopy -i "$S/esp.img" fw/OVMF_CODE.fd fw/OVMF_VARS.fd ::/EFI/hype/
mcopy -i "$S/esp.img" "$ISO" ::/iso/test.iso
mcopy -i "$S/esp.img" tools/qemu-cd-hype.cfg ::/hype.cfg

# The USB stick and the HOST varstore are staged per attempt, in the retry loop below -- the host
# varstore must be the pair of the HOST's CODE (#288's trap), and both must be pristine per attempt.

# #371/#581: roughly one QEMU boot in four on this host never reaches hype at all (SIGSEGV in
# QEMU's own ahci_commit_buf(), qemu-project/qemu#437, fixed in QEMU 11.1.0 -- this host is below
# that). Such a boot is INVALID, not failed: hype was never entered, so nothing about it was under
# test. Retry it, bounded, and never score it. The first run of this script hit exactly that and
# correctly refused to report a result -- which is right, but a rig that needs a human to re-run it
# is a rig that gets read as a failure.
BOOT_ATTEMPTS="${BOOT_ATTEMPTS:-3}"
LOG="$S/serial.txt"
attempt=1
while :; do
    echo "=== booting for ${SECS}s (host reboots at ${REBOOT_AT}s), attempt $attempt ==="
    # A fresh USB stick and host varstore per attempt: a retry must start from the same state the
    # first attempt did, or the "saved on boot 1, restored on boot 2" sequence is not what it says.
    rm -f "$S/usb.img" "$LOG"
    dd if=/dev/zero of="$S/usb.img" bs=1M count=64 status=none
    mkfs.vfat -F 32 -n HYPEUSB "$S/usb.img" >/dev/null
    cp "$OVMF_VARS" "$S/VARS.fd"
    # -vga std, not none: with `none` hype's display path never runs at all, which is how #370's
    # rdmsr #GP hid behind what looked like a render stall.
    timeout "$SECS" qemu-system-x86_64 \
      -machine q35 -m 4096 -nodefaults \
      -accel kvm -cpu host -smp 4 \
      -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE" \
      -drive if=pflash,format=raw,file="$S/VARS.fd" \
      -drive format=raw,file="$S/esp.img",if=none,id=esp \
      -device ide-hd,drive=esp,bus=ide.0,bootindex=0 \
      -device qemu-xhci,id=xhci \
      -drive format=raw,file="$S/usb.img",if=none,id=stick \
      -device usb-storage,bus=xhci.0,drive=stick \
      -serial "file:$LOG" -display none -vga std >/dev/null 2>&1 || true
    grep -aq '^hype: build' "$LOG" && break
    if [ "$attempt" -ge "$BOOT_ATTEMPTS" ]; then
        echo "INVALID: the firmware never launched hype in $BOOT_ATTEMPTS attempts (#371)."
        echo "  Not a hype result and must not be scored. Log: $LOG"
        exit 2
    fi
    echo "  no hype banner (#371) -- retrying, attempt $((attempt + 1)) of $BOOT_ATTEMPTS"
    attempt=$((attempt + 1))
done

echo "=== files left on the USB stick ==="
mdir -i "$S/usb.img" :: || true

rc=0
boots=$(grep -ac '^hype: build' "$LOG" || true)
echo
echo "boots (banner):  $boots"
if [ "$boots" -lt 2 ]; then
    echo "INVALID: the host did not reboot within ${SECS}s (banners=$boots) -- nothing to verify."
    echo "  Raise the timeout or lower REBOOT_AT. Not a result. Log: $LOG"
    exit 2
fi

# 1. saved, and 2. restored AFTER the second banner. `grep -n` line numbers order the two events
#    against the banner without needing timestamps hype does not print.
saved=$(grep -ac 'VARS: vars-.*saved' "$LOG" || true)
second_banner=$(grep -an '^hype: build' "$LOG" | sed -n 2p | cut -d: -f1)
restored_after=$(awk -v n="$second_banner" 'NR>n && /VARS: vars-.*restored/' "$LOG" | wc -l)
echo "saved lines:     $saved"
echo "restored lines after boot 2's banner (line $second_banner): $restored_after"
[ "$saved" -ge 1 ] || { echo "FAIL: no varstore was ever saved"; rc=1; }
[ "$restored_after" -ge 1 ] || { echo "FAIL: no varstore restored on a later boot of the host"; rc=1; }

# 3. the saved image must not be the pristine one this build ships.
echo "=== saved image vs the pristine fw/OVMF_VARS.fd ==="
any=0
for f in $(mdir -i "$S/usb.img" :: 2>/dev/null | awk '/VARS/ {print $1"."$2}' | tr -d ' '); do
    case "$f" in VARS*|vars*) ;; *) continue ;; esac
    any=1
    mtype -i "$S/usb.img" "::/$f" > "$S/saved-$f.bin" 2>/dev/null || continue
    if cmp -s "$S/saved-$f.bin" fw/OVMF_VARS.fd; then
        echo "FAIL: $f is byte-identical to the pristine fw/OVMF_VARS.fd -- the guest firmware's"
        echo "  own variable writes are NOT in it, so the two log lines above prove only that the"
        echo "  save/restore code ran, not that anything persisted."
        rc=1
    else
        echo "OK: $f differs from pristine ($(stat -c%s "$S/saved-$f.bin") bytes) -- it carries the"
        echo "  guest firmware's own writes, so there was real state to lose and it was not lost."
    fi
done
[ "$any" = 1 ] || { echo "FAIL: no vars-*.bin on the stick at all"; rc=1; }

echo
if [ "$rc" = 0 ]; then
    echo "PASS (#119): a VM's varstore survived a host reboot. Log: $LOG"
else
    echo "FAIL (#119). Log: $LOG"
fi
exit $rc
