#include <stdio.h>
#include <string.h>

#include "../blk_qcow2.h"

static int failures = 0;

#define CHECK_INT(desc, expected, actual)                                                          \
    do {                                                                                           \
        long long e_ = (long long)(expected), a_ = (long long)(actual);                             \
        if (e_ != a_) {                                                                            \
            printf("FAIL: %s: expected %lld, got %lld\n", (desc), e_, a_);                          \
            failures++;                                                                            \
        }                                                                                          \
    } while (0)

/*
 * A synthetic qcow2 image, assembled byte by byte. Built here rather than generated by
 * qemu-img so the suite stays deterministic and needs no external tool -- the format
 * arithmetic is exactly what these tests exist to pin, and a fixture that could vary
 * between machines would make a mapping bug look like an environment difference.
 *
 * Geometry: 4 KiB clusters (512 L2 entries, so one L2 table covers 2 MiB), a 4 MiB
 * virtual disk (2 L1 entries), in a 256 KiB file (64 clusters).
 *
 *   cluster 0  header
 *   cluster 1  refcount table
 *   cluster 2  refcount block
 *   cluster 3  L1 table
 *   cluster 4+ free
 */
#define CB 12u
#define CSZ (1u << CB)
#define FILE_CLUSTERS 64u
#define FILE_BYTES (FILE_CLUSTERS * CSZ)
#define VIRT_BYTES (4u * 1024u * 1024u)
#define RC_TABLE_CLUSTER 1u
#define RC_BLOCK_CLUSTER 2u
#define L1_CLUSTER 3u
#define FIRST_FREE 4u
#define QCOW2_HDR_RC_TABLE_OFF 48u

typedef struct {
    uint8_t bytes[FILE_BYTES];
    int reject_writes;
    /*
     * Fault injection: fail the Nth read/write. -1 disables. `fired` records that the
     * fault was actually reached, which is what lets a test assert the sharp property --
     * every I/O failure the layer below reports must surface as a refusal, never as a
     * success built on data that was never read.
     */
    int reads_until_fail;
    int writes_until_fail;
    int fired;
} fake_file_t;

static fake_file_t g_file;

static int fake_read(void *ctx, uint64_t lba, uint32_t count, void *buf) {
    fake_file_t *f = (fake_file_t *)ctx;
    if (f->reads_until_fail > 0 && --f->reads_until_fail == 0) {
        f->fired = 1;
        return -1;
    }
    memcpy(buf, &f->bytes[lba * 512u], (size_t)count * 512u);
    return 0;
}

static int fake_write(void *ctx, uint64_t lba, uint32_t count, const void *buf) {
    fake_file_t *f = (fake_file_t *)ctx;
    if (f->reject_writes) {
        return -1;
    }
    if (f->writes_until_fail > 0 && --f->writes_until_fail == 0) {
        f->fired = 1;
        return -1;
    }
    memcpy(&f->bytes[lba * 512u], buf, (size_t)count * 512u);
    return 0;
}

static void put32(uint8_t *p, uint32_t v) {
    p[0] = (uint8_t)(v >> 24);
    p[1] = (uint8_t)(v >> 16);
    p[2] = (uint8_t)(v >> 8);
    p[3] = (uint8_t)v;
}

static void put64(uint8_t *p, uint64_t v) {
    put32(p, (uint32_t)(v >> 32));
    put32(p + 4, (uint32_t)v);
}

static uint64_t get64(const uint8_t *p) {
    uint64_t v = 0;
    unsigned int i;
    for (i = 0; i < 8u; i++) {
        v = (v << 8) | p[i];
    }
    return v;
}

static uint16_t refcount_of(uint64_t cluster_idx) {
    /* One refcount block in this image, so the entry index is the cluster index. */
    const uint8_t *e = &g_file.bytes[RC_BLOCK_CLUSTER * CSZ + cluster_idx * 2u];
    return (uint16_t)((e[0] << 8) | e[1]);
}

/* Reset the fake file to a valid, freshly-created v3 image. */
static void build_image(void) {
    uint8_t *h = g_file.bytes;

    memset(&g_file, 0, sizeof(g_file));
    g_file.reject_writes = 0;
    g_file.reads_until_fail = -1;
    g_file.writes_until_fail = -1;
    g_file.fired = 0;

    put32(h + 0, HYPE_QCOW2_MAGIC);
    put32(h + 4, 3u);                     /* version */
    put64(h + 8, 0u);                     /* backing_file_offset */
    put32(h + 16, 0u);                    /* backing_file_size */
    put32(h + 20, CB);                    /* cluster_bits */
    put64(h + 24, VIRT_BYTES);            /* virtual size */
    put32(h + 32, 0u);                    /* crypt_method */
    put32(h + 36, 2u);                    /* l1_size */
    put64(h + 40, (uint64_t)L1_CLUSTER * CSZ);
    put64(h + 48, (uint64_t)RC_TABLE_CLUSTER * CSZ);
    put32(h + 56, 1u);                    /* refcount_table_clusters */
    put32(h + 60, 0u);                    /* nb_snapshots */
    put64(h + 72, 0u);                    /* incompatible_features */
    put32(h + 96, 4u);                    /* refcount_order */
    put32(h + 100, 104u);                 /* header_length */

    /* Refcount table entry 0 -> the one refcount block. */
    put64(&g_file.bytes[RC_TABLE_CLUSTER * CSZ], (uint64_t)RC_BLOCK_CLUSTER * CSZ);
    /* Clusters 0..3 are in use. */
    {
        unsigned int c;
        for (c = 0; c < FIRST_FREE; c++) {
            uint8_t *e = &g_file.bytes[RC_BLOCK_CLUSTER * CSZ + c * 2u];
            e[0] = 0;
            e[1] = 1;
        }
    }
}

static hype_qcow2_t g_q;
static hype_blk_backend_t g_be;
static hype_blk_backend_t g_file_be;

static int open_image(void) {
    g_file_be.read = fake_read;
    g_file_be.write = fake_write;
    g_file_be.ctx = &g_file;
    g_file_be.total_sectors = FILE_BYTES / 512u;
    return hype_qcow2_init(&g_q, &g_be, &g_file_be, 0);
}

static void test_init_reports_virtual_geometry(void) {
    build_image();
    CHECK_INT("init accepts a fresh v3 image", 0, open_image());
    CHECK_INT("capacity is the VIRTUAL size, not the allocated size", VIRT_BYTES / 512u,
              (long long)g_be.total_sectors);
    CHECK_INT("cluster size parsed", CSZ, (long long)g_q.cluster_size);
    /* The allocation cursor comes from the refcount map, because qcow2 stores no
     * end-of-data marker and the backing file is deliberately oversized. */
    CHECK_INT("allocation cursor derived from refcounts", FIRST_FREE,
              (long long)g_q.next_free_cluster);
    CHECK_INT("writable image exposes write", 1, g_be.write != 0);
}

static void test_unallocated_reads_as_zeros(void) {
    uint8_t buf[1024];

    build_image();
    CHECK_INT("init", 0, open_image());
    memset(buf, 0xEE, sizeof(buf));
    CHECK_INT("read of an unwritten region succeeds", 0,
              hype_blk_backend_read(&g_be, 0, 2, buf));
    {
        unsigned int i, nonzero = 0;
        for (i = 0; i < sizeof(buf); i++) {
            if (buf[i] != 0u) {
                nonzero++;
            }
        }
        CHECK_INT("unwritten region reads as zeros", 0, (long long)nonzero);
    }
    /* And the mapper says so, rather than pointing at cluster 0 (the header). */
    {
        uint64_t off = 0xDEADu;
        CHECK_INT("map reports unallocated", 0, hype_qcow2_map(&g_q, 0, &off));
        CHECK_INT("map left the output untouched", 0xDEAD, (long long)off);
    }
}

static void test_write_allocates_l2_and_data_then_reads_back(void) {
    uint8_t out[512];
    uint8_t in[512];
    unsigned int i;

    build_image();
    CHECK_INT("init", 0, open_image());
    for (i = 0; i < 512u; i++) {
        in[i] = (uint8_t)(i ^ 0x5Au);
    }
    CHECK_INT("write sector 0", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    /* Two clusters consumed: the L2 table, then the data cluster. */
    CHECK_INT("L2 + data allocated", FIRST_FREE + 2u, (long long)g_q.next_free_cluster);
    CHECK_INT("L2 cluster refcounted", 1, refcount_of(FIRST_FREE));
    CHECK_INT("data cluster refcounted", 1, refcount_of(FIRST_FREE + 1u));

    memset(out, 0, sizeof(out));
    CHECK_INT("read back", 0, hype_blk_backend_read(&g_be, 0, 1, out));
    CHECK_INT("data survives the round trip", 0, memcmp(in, out, 512u));

    /* L1 and L2 entries must carry the COPIED bit, or qemu would treat the clusters as
     * shared with a snapshot and refuse to write them in place. */
    CHECK_INT("L1 entry has COPIED", 1,
              (get64(&g_file.bytes[L1_CLUSTER * CSZ]) >> 63) & 1u);
    CHECK_INT("L2 entry has COPIED", 1,
              (get64(&g_file.bytes[(uint64_t)FIRST_FREE * CSZ]) >> 63) & 1u);
}

static void test_second_write_in_same_cluster_reuses_it(void) {
    uint8_t in[512];

    build_image();
    CHECK_INT("init", 0, open_image());
    memset(in, 0xA1, sizeof(in));
    CHECK_INT("write sector 0", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    CHECK_INT("after first write", FIRST_FREE + 2u, (long long)g_q.next_free_cluster);
    /* Sector 1 is in the same 4 KiB cluster, so nothing new may be allocated -- that is
     * the whole point of a cluster-based format. */
    memset(in, 0xB2, sizeof(in));
    CHECK_INT("write sector 1", 0, hype_blk_backend_write(&g_be, 1, 1, in));
    CHECK_INT("same cluster reused", FIRST_FREE + 2u, (long long)g_q.next_free_cluster);
    {
        uint8_t out[512];
        CHECK_INT("read sector 1", 0, hype_blk_backend_read(&g_be, 1, 1, out));
        CHECK_INT("sector 1 content", 0, memcmp(in, out, 512u));
        memset(in, 0xA1, sizeof(in));
        CHECK_INT("read sector 0", 0, hype_blk_backend_read(&g_be, 0, 1, out));
        CHECK_INT("sector 0 untouched by the sector-1 write", 0, memcmp(in, out, 512u));
    }
}

static void test_partial_cluster_write_zeroes_the_rest(void) {
    /* The new cluster is handed out from a pre-allocated file that may contain anything.
     * The sectors the guest did NOT write must read back as zeros, not as whatever was
     * in the image file at that offset. */
    uint8_t in[512];
    uint8_t out[512];
    unsigned int i, nonzero = 0;

    build_image();
    /* Poison the cluster that will be handed out as the data cluster. */
    memset(&g_file.bytes[(uint64_t)(FIRST_FREE + 1u) * CSZ], 0x77, CSZ);
    CHECK_INT("init", 0, open_image());
    memset(in, 0xC3, sizeof(in));
    CHECK_INT("write one sector of the cluster", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    CHECK_INT("read a sector the guest never wrote", 0, hype_blk_backend_read(&g_be, 3, 1, out));
    for (i = 0; i < 512u; i++) {
        if (out[i] != 0u) {
            nonzero++;
        }
    }
    CHECK_INT("unwritten part of an allocated cluster reads as zeros", 0, (long long)nonzero);
}

static void test_write_spanning_a_cluster_boundary(void) {
    /* 4 KiB clusters, so sectors 7 and 8 straddle a boundary: two clusters, two
     * allocations, one guest request. */
    uint8_t in[1024];
    uint8_t out[1024];
    unsigned int i;

    build_image();
    CHECK_INT("init", 0, open_image());
    for (i = 0; i < sizeof(in); i++) {
        in[i] = (uint8_t)(i * 7u + 1u);
    }
    CHECK_INT("write across the boundary", 0, hype_blk_backend_write(&g_be, 7, 2, in));
    /* One L2 table + two data clusters. */
    CHECK_INT("two data clusters allocated", FIRST_FREE + 3u, (long long)g_q.next_free_cluster);
    CHECK_INT("read across the boundary", 0, hype_blk_backend_read(&g_be, 7, 2, out));
    CHECK_INT("both halves survive", 0, memcmp(in, out, sizeof(in)));
}

static void test_write_in_second_l1_entry(void) {
    /* One L2 table covers 2 MiB; the 4 MiB disk needs the second L1 entry, and a write
     * there must allocate its own L2 table rather than reusing the first. */
    uint8_t in[512];
    uint8_t out[512];
    uint64_t high_lba = (2u * 1024u * 1024u) / 512u;

    build_image();
    CHECK_INT("init", 0, open_image());
    memset(in, 0x5C, sizeof(in));
    CHECK_INT("write into the low L1 entry", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    memset(in, 0x9D, sizeof(in));
    CHECK_INT("write into the high L1 entry", 0, hype_blk_backend_write(&g_be, high_lba, 1, in));
    CHECK_INT("second L2 table allocated", FIRST_FREE + 4u, (long long)g_q.next_free_cluster);
    CHECK_INT("read the high sector", 0, hype_blk_backend_read(&g_be, high_lba, 1, out));
    CHECK_INT("high sector content", 0, memcmp(in, out, 512u));
    CHECK_INT("second L1 entry populated", 1,
              (get64(&g_file.bytes[L1_CLUSTER * CSZ + 8u]) & 0x00FFFFFFFFFFFE00ULL) != 0u);
}

static void test_zero_flagged_cluster_reads_as_zeros(void) {
    uint8_t out[512];
    unsigned int i, nonzero = 0;

    build_image();
    /* Hand-build an L2 table whose entry 0 points at real data but is flagged
     * all-zeroes. qemu writes this when a guest discards a range. */
    put64(&g_file.bytes[L1_CLUSTER * CSZ], ((uint64_t)FIRST_FREE * CSZ) | (1ULL << 63));
    put64(&g_file.bytes[(uint64_t)FIRST_FREE * CSZ],
          ((uint64_t)(FIRST_FREE + 1u) * CSZ) | (1ULL << 63) | 1ULL);
    memset(&g_file.bytes[(uint64_t)(FIRST_FREE + 1u) * CSZ], 0xFF, CSZ);
    CHECK_INT("init", 0, open_image());
    CHECK_INT("read a zero-flagged cluster", 0, hype_blk_backend_read(&g_be, 0, 1, out));
    for (i = 0; i < 512u; i++) {
        if (out[i] != 0u) {
            nonzero++;
        }
    }
    CHECK_INT("zero flag wins over the cluster's contents", 0, (long long)nonzero);
    {
        uint64_t off = 0;
        CHECK_INT("map treats it as unallocated", 0, hype_qcow2_map(&g_q, 0, &off));
    }
}

static void test_compressed_cluster_is_refused(void) {
    uint64_t off = 0;
    uint8_t out[512];

    build_image();
    put64(&g_file.bytes[L1_CLUSTER * CSZ], ((uint64_t)FIRST_FREE * CSZ) | (1ULL << 63));
    put64(&g_file.bytes[(uint64_t)FIRST_FREE * CSZ],
          ((uint64_t)(FIRST_FREE + 1u) * CSZ) | (1ULL << 62));
    CHECK_INT("init", 0, open_image());
    /* Refused, not served as raw bytes: there is no decompressor, and handing the guest
     * compressed bytes as if they were data corrupts silently. */
    CHECK_INT("map refuses a compressed cluster", -1, hype_qcow2_map(&g_q, 0, &off));
    CHECK_INT("read refuses a compressed cluster", -1, hype_blk_backend_read(&g_be, 0, 1, out));
}

static void test_shared_cluster_write_is_refused(void) {
    uint8_t in[512];

    build_image();
    /* COPIED clear on the L2 entry means the cluster is shared (refcount > 1). Writing
     * it in place would alter whatever else references it. */
    put64(&g_file.bytes[L1_CLUSTER * CSZ], ((uint64_t)FIRST_FREE * CSZ) | (1ULL << 63));
    put64(&g_file.bytes[(uint64_t)FIRST_FREE * CSZ], (uint64_t)(FIRST_FREE + 1u) * CSZ);
    CHECK_INT("init", 0, open_image());
    memset(in, 0x11, sizeof(in));
    CHECK_INT("write to a shared data cluster refused", -1,
              hype_blk_backend_write(&g_be, 0, 1, in));
    /* Reading it is still fine -- only the in-place write is unsafe. */
    {
        uint8_t out[512];
        CHECK_INT("read of a shared cluster still works", 0,
                  hype_blk_backend_read(&g_be, 0, 1, out));
    }
}

static void test_shared_l2_table_write_is_refused(void) {
    uint8_t in[512];

    build_image();
    put64(&g_file.bytes[L1_CLUSTER * CSZ], (uint64_t)FIRST_FREE * CSZ); /* no COPIED */
    CHECK_INT("init", 0, open_image());
    memset(in, 0x22, sizeof(in));
    CHECK_INT("write through a shared L2 table refused", -1,
              hype_blk_backend_write(&g_be, 0, 1, in));
}

static void test_image_full_is_refused_not_written_outside(void) {
    uint8_t in[512];
    uint64_t lba;
    int saw_refusal = 0;

    build_image();
    CHECK_INT("init", 0, open_image());
    memset(in, 0x33, sizeof(in));
    /* Each fresh cluster costs one allocation (plus an L2 table per 2 MiB), so walking
     * the disk one cluster at a time exhausts the 64-cluster file well before the 4 MiB
     * virtual size. The point is that it REFUSES rather than allocating past the file. */
    for (lba = 0; lba < VIRT_BYTES / 512u; lba += CSZ / 512u) {
        if (hype_blk_backend_write(&g_be, lba, 1, in) != 0) {
            saw_refusal = 1;
            break;
        }
    }
    CHECK_INT("a full image refuses further allocation", 1, saw_refusal);
    CHECK_INT("cursor never passed the file's capacity", 1,
              g_q.next_free_cluster <= FILE_CLUSTERS);
}

static void test_backing_read_through_and_copy_on_write(void) {
    static uint8_t backing_bytes[VIRT_BYTES / 8u];
    static fake_file_t backing_file;
    static hype_blk_backend_t backing_be;
    uint8_t out[512];
    uint8_t in[512];
    unsigned int i;

    (void)backing_bytes;
    memset(&backing_file, 0, sizeof(backing_file));
    for (i = 0; i < CSZ; i++) {
        backing_file.bytes[i] = (uint8_t)(0x40u + (i & 0x0Fu));
    }
    backing_be.read = fake_read;
    backing_be.write = 0;
    backing_be.ctx = &backing_file;
    backing_be.total_sectors = sizeof(backing_file.bytes) / 512u;

    build_image();
    g_file_be.read = fake_read;
    g_file_be.write = fake_write;
    g_file_be.ctx = &g_file;
    g_file_be.total_sectors = FILE_BYTES / 512u;
    CHECK_INT("init with a backing image", 0,
              hype_qcow2_init(&g_q, &g_be, &g_file_be, &backing_be));

    /* Unallocated here: the read must come from the chain, not from zeros. */
    CHECK_INT("read through to the backing image", 0, hype_blk_backend_read(&g_be, 1, 1, out));
    CHECK_INT("backing data delivered", 0, memcmp(out, &backing_file.bytes[512u], 512u));

    /* Writing one sector must copy the WHOLE cluster forward first, or the sectors the
     * guest did not write would come back as zeros instead of the chain's data. */
    memset(in, 0x99, sizeof(in));
    CHECK_INT("write over a backed cluster", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    CHECK_INT("written sector", 0, hype_blk_backend_read(&g_be, 0, 1, out));
    CHECK_INT("written sector holds the new data", 0, memcmp(out, in, 512u));
    CHECK_INT("neighbour sector", 0, hype_blk_backend_read(&g_be, 1, 1, out));
    CHECK_INT("neighbour still shows the backing data (copy-on-write)", 0,
              memcmp(out, &backing_file.bytes[512u], 512u));
}

static void test_header_refusals(void) {
    struct {
        const char *desc;
        unsigned int off;
        int width; /* 4 or 8 */
        uint64_t value;
    } cases[] = {
        {"bad magic", 0u, 4, 0x12345678u},
        {"version 1", 4u, 4, 1u},
        {"version 4", 4u, 4, 4u},
        {"cluster_bits too small", 20u, 4, 8u},
        {"cluster_bits too large", 20u, 4, 22u},
        {"encrypted", 32u, 4, 1u},
        {"has snapshots", 60u, 4, 1u},
        {"incompatible feature set", 72u, 8, 1u},
        {"refcount_order not 4", 96u, 4, 5u},
        {"l1_size too small for the virtual size", 36u, 4, 1u},
        {"zero virtual size", 24u, 8, 0u},
        {"null l1 offset", 40u, 8, 0u},
        {"null refcount table offset", 48u, 8, 0u},
        {"zero refcount table clusters", 56u, 4, 0u},
        {"misaligned l1 offset", 40u, 8, (uint64_t)L1_CLUSTER * CSZ + 512u},
        {"backing file named but not supplied", 16u, 4, 32u},
    };
    unsigned int c;

    for (c = 0; c < sizeof(cases) / sizeof(cases[0]); c++) {
        build_image();
        if (cases[c].width == 4) {
            put32(&g_file.bytes[cases[c].off], (uint32_t)cases[c].value);
        } else {
            put64(&g_file.bytes[cases[c].off], cases[c].value);
        }
        CHECK_INT(cases[c].desc, -1, open_image());
    }
}

static void test_readonly_file_yields_readonly_backend(void) {
    build_image();
    g_file_be.read = fake_read;
    g_file_be.write = 0;
    g_file_be.ctx = &g_file;
    g_file_be.total_sectors = FILE_BYTES / 512u;
    CHECK_INT("init over a read-only file", 0, hype_qcow2_init(&g_q, &g_be, &g_file_be, 0));
    /* NULL rather than a write that discovers it cannot persist halfway through an
     * allocation, having already rewritten the L1 table. */
    CHECK_INT("backend is read-only", 1, g_be.write == 0);
    {
        uint8_t in[512];
        memset(in, 1, sizeof(in));
        CHECK_INT("dispatcher rejects the write", -1, hype_blk_backend_write(&g_be, 0, 1, in));
    }
}

static void test_init_argument_and_io_failures(void) {
    build_image();
    CHECK_INT("NULL q", -1, hype_qcow2_init(0, &g_be, &g_file_be, 0));
    CHECK_INT("NULL be", -1, hype_qcow2_init(&g_q, 0, &g_file_be, 0));
    CHECK_INT("NULL file", -1, hype_qcow2_init(&g_q, &g_be, 0, 0));

    /* A file too small to hold one cluster cannot be a qcow2 image. */
    g_file_be.read = fake_read;
    g_file_be.write = fake_write;
    g_file_be.ctx = &g_file;
    g_file_be.total_sectors = 1u;
    CHECK_INT("file smaller than a cluster", -1, hype_qcow2_init(&g_q, &g_be, &g_file_be, 0));

    /* A write failure from the layer below must propagate, not be swallowed. */
    build_image();
    CHECK_INT("init", 0, open_image());
    g_file.reject_writes = 1;
    {
        uint8_t in[512];
        memset(in, 4, sizeof(in));
        CHECK_INT("host write error propagates", -1, hype_blk_backend_write(&g_be, 0, 1, in));
    }
}

static void test_reopen_sees_previous_allocations(void) {
    /* The allocation cursor is derived, not stored, so a fresh open of an image that has
     * already been written must not hand out clusters that are in use -- otherwise a
     * second boot would overwrite the first boot's data. */
    uint8_t in[512];
    uint64_t cursor_after_write;

    build_image();
    CHECK_INT("init", 0, open_image());
    memset(in, 0x6E, sizeof(in));
    CHECK_INT("write", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    cursor_after_write = g_q.next_free_cluster;

    CHECK_INT("reopen", 0, open_image());
    CHECK_INT("reopen recovers the cursor", (long long)cursor_after_write,
              (long long)g_q.next_free_cluster);
    {
        uint8_t out[512];
        CHECK_INT("data still readable after reopen", 0, hype_blk_backend_read(&g_be, 0, 1, out));
        CHECK_INT("data intact after reopen", 0, memcmp(in, out, 512u));
    }
}

static void test_v2_image_without_v3_fields(void) {
    /* qcow2 v2 has no incompatible_features or refcount_order field, so those must not
     * be read for a v2 header -- a v2 image with nonzero bytes at those offsets is
     * still valid. */
    build_image();
    put32(&g_file.bytes[4], 2u);
    put64(&g_file.bytes[72], 0xFFFFFFFFFFFFFFFFULL);
    put32(&g_file.bytes[96], 9u);
    CHECK_INT("v2 image accepted", 0, open_image());
    CHECK_INT("v2 version recorded", 2, (long long)g_q.version);
}

/*
 * A second, smaller geometry: 512-byte clusters, so one refcount block covers only 256
 * clusters and a modest number of writes forces a SECOND refcount block to be created.
 * That path -- allocating a refcount block, installing its table entry, and giving the
 * block cluster its own refcount -- is the one qemu-img check would flag as a leaked or
 * unaccounted cluster if it were wrong, and it is unreachable at 4 KiB clusters without
 * an 8 MiB test image.
 *
 *   cluster 0 header, 1 refcount table, 2 refcount block, 3 L1 table, 4+ free
 */
#define CB2 9u
#define CSZ2 512u
#define FILE2_CLUSTERS 320u
/* 8 MiB virtual: enough distinct 512-byte clusters (16384) that allocation can exhaust
 * a one-cluster refcount table, which is what test_refcount_table_too_small_is_refused
 * needs to reach. */
#define VIRT2_BYTES (8u * 1024u * 1024u)
#define L1_2_ENTRIES 256u
#define FIRST_FREE2 7u /* header, refcount table, refcount block, then 4 L1 clusters */

/*
 * Sparse: sectors past the materialised array read as zeros and writes to them are
 * discarded. That models a file LARGER than the test wants to hold in memory, which is
 * what the refcount-table-overflow case needs -- reaching that guard means allocating
 * past cluster 16383, i.e. an 8 MiB image, and only the guard itself is interesting
 * there. `capacity_sectors` is what the backend is told, independently of the array.
 */
typedef struct {
    uint8_t bytes[FILE2_CLUSTERS * CSZ2];
    uint64_t capacity_sectors;
    int reads_until_fail;
    int writes_until_fail;
    int fired;
} fake_file2_t;

static fake_file2_t g_file2;

static int fake2_read(void *ctx, uint64_t lba, uint32_t count, void *buf) {
    fake_file2_t *f = (fake_file2_t *)ctx;
    if (f->reads_until_fail > 0 && --f->reads_until_fail == 0) {
        f->fired = 1;
        return -1;
    }
    if ((lba + count) * 512u > sizeof(f->bytes)) {
        memset(buf, 0, (size_t)count * 512u);
        return 0;
    }
    memcpy(buf, &f->bytes[lba * 512u], (size_t)count * 512u);
    return 0;
}

static int fake2_write(void *ctx, uint64_t lba, uint32_t count, const void *buf) {
    fake_file2_t *f = (fake_file2_t *)ctx;
    if (f->writes_until_fail > 0 && --f->writes_until_fail == 0) {
        f->fired = 1;
        return -1;
    }
    if ((lba + count) * 512u > sizeof(f->bytes)) {
        return 0;
    }
    memcpy(&f->bytes[lba * 512u], buf, (size_t)count * 512u);
    return 0;
}

/* Build the small-cluster image into g_file2 and open it. `capacity_clusters` is what
 * the backend is told the file holds. */
static int open_image2(hype_qcow2_t *q, hype_blk_backend_t *be, hype_blk_backend_t *file_be,
                       uint64_t capacity_clusters) {
    uint8_t *h = g_file2.bytes;
    unsigned int k;

    memset(&g_file2, 0, sizeof(g_file2));
    g_file2.reads_until_fail = -1;
    g_file2.writes_until_fail = -1;
    put32(h + 0, HYPE_QCOW2_MAGIC);
    put32(h + 4, 3u);
    put32(h + 20, CB2);
    put64(h + 24, VIRT2_BYTES);
    put32(h + 36, L1_2_ENTRIES); /* 256 * (64 * 512) = 8 MiB */
    put64(h + 40, 3u * CSZ2);   /* L1 table spans clusters 3..6 */
    put64(h + 48, 1u * CSZ2);
    put32(h + 56, 1u);
    put32(h + 96, 4u);
    put32(h + 100, 104u);
    put64(&g_file2.bytes[1u * CSZ2], 2u * CSZ2); /* refcount table -> block */
    for (k = 0; k < FIRST_FREE2; k++) {
        g_file2.bytes[2u * CSZ2 + k * 2u + 1u] = 1u; /* header, tables, L1 all in use */
    }
    file_be->read = fake2_read;
    file_be->write = fake2_write;
    file_be->ctx = &g_file2;
    file_be->total_sectors = capacity_clusters * (CSZ2 / 512u);
    return hype_qcow2_init(q, be, file_be, 0);
}

static void test_second_refcount_block_is_created(void) {
    hype_qcow2_t q;
    hype_blk_backend_t be;
    hype_blk_backend_t file_be;
    uint8_t in[512];
    uint8_t out[512];
    unsigned int k;
    int wrote_all = 1;

    CHECK_INT("small-cluster image opens", 0, open_image2(&q, &be, &file_be, FILE2_CLUSTERS));

    /* 256 sectors = 256 distinct 512-byte clusters, plus one L2 table per 64 of them:
     * 260 allocations from cluster 7, so the last ones land past cluster 255 and need a
     * refcount block that does not exist yet. */
    for (k = 0; k < 256u; k++) {
        memset(in, (uint8_t)(k + 1u), sizeof(in));
        if (hype_blk_backend_write(&be, k, 1, in) != 0) {
            wrote_all = 0;
            break;
        }
    }
    CHECK_INT("all 256 clusters written", 1, wrote_all);
    CHECK_INT("allocation crossed the first refcount block", 1, q.next_free_cluster > 256u);
    /* The second refcount block must now exist and account for the clusters past 255. */
    CHECK_INT("second refcount table entry populated", 1,
              (get64(&g_file2.bytes[1u * CSZ2 + 8u]) & 0x00FFFFFFFFFFFE00ULL) != 0u);
    {
        uint64_t blk2 = get64(&g_file2.bytes[1u * CSZ2 + 8u]) & 0x00FFFFFFFFFFFE00ULL;
        const uint8_t *e = &g_file2.bytes[blk2]; /* entry 0 == cluster 256 */
        CHECK_INT("cluster 256 refcounted in the new block", 1, (e[0] << 8) | e[1]);
    }
    /* And every sector must still read back as written -- the crossing must not have
     * disturbed anything already allocated. */
    for (k = 0; k < 256u; k++) {
        memset(in, (uint8_t)(k + 1u), sizeof(in));
        CHECK_INT("read back", 0, hype_blk_backend_read(&be, k, 1, out));
        if (memcmp(in, out, sizeof(in)) != 0) {
            printf("FAIL: sector %u did not survive the refcount-block crossing\\n", k);
            failures++;
            break;
        }
    }
}

static void test_refcount_table_too_small_is_refused(void) {
    /*
     * One refcount table cluster addresses 64 blocks of 256 clusters = 16384 clusters.
     * Told the file is bigger than that, allocation eventually needs a 65th block, which
     * would mean growing the refcount table -- refused, because writing past the table
     * would corrupt whatever cluster follows it.
     */
    hype_qcow2_t q;
    hype_blk_backend_t be;
    hype_blk_backend_t file_be;
    uint8_t in[512];
    unsigned int k;
    int refused = 0;

    CHECK_INT("oversized-capacity image opens", 0, open_image2(&q, &be, &file_be, 20000u));
    memset(in, 0x8A, sizeof(in));
    /* One 512-byte cluster per sector, so walking the whole 8 MiB virtual disk allocates
     * more clusters than one refcount table can account for. */
    for (k = 0; k < 16384u; k++) {
        if (hype_blk_backend_write(&be, k, 1, in) != 0) {
            refused = 1;
            break;
        }
    }
    CHECK_INT("refcount table exhaustion is refused", 1, refused);
    CHECK_INT("refusal happened past the first table's reach", 1, q.next_free_cluster > 16000u);
}

static void test_io_failures_surface_during_refcount_block_creation(void) {
    /*
     * Same sweep as test_every_io_failure_surfaces, on the geometry that actually
     * exercises refcount-block CREATION -- the deepest allocation path here, where a
     * swallowed error would leave the refcount table pointing at a block whose contents
     * were never written.
     */
    unsigned int n;

    for (n = 1u; n <= 1400u; n++) {
        hype_qcow2_t q;
        hype_blk_backend_t be;
        hype_blk_backend_t file_be;
        uint8_t in[512];
        unsigned int k;
        int rc = open_image2(&q, &be, &file_be, FILE2_CLUSTERS);

        CHECK_INT("init", 0, rc);
        g_file2.writes_until_fail = (int)n;
        memset(in, 0x2B, sizeof(in));
        for (k = 0; k < 256u; k++) {
            rc = hype_blk_backend_write(&be, k, 1, in);
            if (rc != 0) {
                break;
            }
        }
        if (g_file2.fired && rc == 0) {
            printf("FAIL: write failure #%u swallowed during refcount-block creation\\n", n);
            failures++;
        }
    }
    for (n = 1u; n <= 1400u; n++) {
        hype_qcow2_t q;
        hype_blk_backend_t be;
        hype_blk_backend_t file_be;
        uint8_t in[512];
        unsigned int k;
        int rc = open_image2(&q, &be, &file_be, FILE2_CLUSTERS);

        CHECK_INT("init", 0, rc);
        g_file2.reads_until_fail = (int)n;
        memset(in, 0x3C, sizeof(in));
        for (k = 0; k < 256u; k++) {
            rc = hype_blk_backend_write(&be, k, 1, in);
            if (rc != 0) {
                break;
            }
        }
        if (g_file2.fired && rc == 0) {
            printf("FAIL: read failure #%u swallowed during refcount-block creation\\n", n);
            failures++;
        }
    }
}

static void test_cursor_never_hands_out_the_metadata_clusters(void) {
    /* An image whose refcount map claims nothing is in use must still not allocate the
     * header, the refcount table or the L1 table. Without the floor the first write
     * would hand out cluster 0 and the next one would overwrite the header. */
    uint8_t in[512];

    build_image();
    memset(&g_file.bytes[RC_BLOCK_CLUSTER * CSZ], 0, CSZ); /* empty the refcount map */
    CHECK_INT("init", 0, open_image());
    CHECK_INT("cursor floored past the metadata", 1, g_q.next_free_cluster > L1_CLUSTER);
    memset(in, 0x44, sizeof(in));
    CHECK_INT("write", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    CHECK_INT("header magic intact", (long long)HYPE_QCOW2_MAGIC,
              (long long)((g_file.bytes[0] << 24) | (g_file.bytes[1] << 16) |
                          (g_file.bytes[2] << 8) | g_file.bytes[3]));
}

static void test_refcount_table_after_the_l1_table(void) {
    /* Nothing requires the refcount table to precede the L1 table; qemu-img's layout
     * happens to, but an image rewritten by another tool need not. The allocation floor
     * has to account for whichever sits higher. */
    uint8_t in[512];

    build_image();
    /* Move the refcount table to cluster 8, past the L1 table at cluster 3. */
    put64(&g_file.bytes[QCOW2_HDR_RC_TABLE_OFF], 8u * (uint64_t)CSZ);
    memcpy(&g_file.bytes[8u * CSZ], &g_file.bytes[RC_TABLE_CLUSTER * CSZ], CSZ);
    memset(&g_file.bytes[RC_TABLE_CLUSTER * CSZ], 0, CSZ);
    CHECK_INT("init with a high refcount table", 0, open_image());
    CHECK_INT("floor accounts for the refcount table's position", 1, g_q.next_free_cluster >= 9u);
    memset(in, 0x66, sizeof(in));
    CHECK_INT("write", 0, hype_blk_backend_write(&g_be, 0, 1, in));
    {
        uint64_t rt = get64(&g_file.bytes[8u * CSZ]);
        CHECK_INT("refcount table entry not overwritten by an allocation", 1,
                  (rt & 0x00FFFFFFFFFFFE00ULL) == (uint64_t)RC_BLOCK_CLUSTER * CSZ);
    }
}

static void test_map_past_the_l1_table(void) {
    uint64_t off = 0x1234u;

    build_image();
    CHECK_INT("init", 0, open_image());
    /* Past the L1 table entirely: unallocated, not an error -- the bounds gate above is
     * what rejects out-of-range guest I/O, and this layer must not double as it. */
    CHECK_INT("offset past the L1 reports unallocated", 0,
              hype_qcow2_map(&g_q, (uint64_t)VIRT_BYTES * 16u, &off));
    CHECK_INT("output untouched", 0x1234, (long long)off);
}

/*
 * Every read/write the layer below can fail must surface as a refusal. Walked as a
 * sweep -- fail the Nth I/O, for every N -- rather than as a handful of hand-picked
 * cases, because the interesting failures are the ones deep inside an allocation, where
 * the L1 entry has already been rewritten and a swallowed error would leave the image
 * pointing at a cluster whose contents were never established.
 */
static void test_every_io_failure_surfaces(void) {
    unsigned int n;

    for (n = 1u; n <= 200u; n++) {
        uint8_t in[512];
        int rc;

        build_image();
        g_file.reads_until_fail = (int)n;
        rc = open_image();
        if (rc == 0) {
            memset(in, 0x5D, sizeof(in));
            rc = hype_blk_backend_write(&g_be, 0, 1, in);
            if (rc == 0) {
                rc = hype_blk_backend_read(&g_be, 0, 1, in);
            }
        }
        if (g_file.fired && rc == 0) {
            printf("FAIL: read failure #%u was swallowed\n", n);
            failures++;
        }
    }
    for (n = 1u; n <= 200u; n++) {
        uint8_t in[512];
        int rc;

        build_image();
        rc = open_image();
        CHECK_INT("init before injecting write faults", 0, rc);
        g_file.writes_until_fail = (int)n;
        memset(in, 0x5E, sizeof(in));
        rc = hype_blk_backend_write(&g_be, 0, 1, in);
        if (rc == 0) {
            rc = hype_blk_backend_write(&g_be, 64, 1, in);
        }
        if (g_file.fired && rc == 0) {
            printf("FAIL: write failure #%u was swallowed\n", n);
            failures++;
        }
    }
}

static void test_read_failures_after_init_surface(void) {
    /* The init sweep above consumes its fault budget inside hype_qcow2_init, so it never
     * reaches the reads the MAPPER and the data path make. Arming the fault after init
     * covers those: an L1 or L2 lookup that fails must refuse, not fall through to
     * "unallocated" and hand the guest zeros where its data actually is. */
    unsigned int n;

    for (n = 1u; n <= 80u; n++) {
        uint8_t in[512];
        int rc;

        build_image();
        CHECK_INT("init", 0, open_image());
        memset(in, 0x7A, sizeof(in));
        CHECK_INT("seed a written cluster", 0, hype_blk_backend_write(&g_be, 0, 1, in));
        g_file.fired = 0;
        g_file.reads_until_fail = (int)n;
        rc = hype_blk_backend_read(&g_be, 0, 1, in);
        if (rc == 0) {
            uint64_t off = 0;
            rc = hype_qcow2_map(&g_q, 0, &off) < 0 ? -1 : 0;
        }
        if (rc == 0) {
            rc = hype_blk_backend_write(&g_be, 64, 1, in);
        }
        if (g_file.fired && rc == 0) {
            printf("FAIL: post-init read failure #%u was swallowed\n", n);
            failures++;
        }
    }
}

static void test_backing_read_failure_surfaces(void) {
    static fake_file_t backing_file;
    static hype_blk_backend_t backing_be;
    uint8_t buf[512];

    memset(&backing_file, 0, sizeof(backing_file));
    backing_file.reads_until_fail = 1; /* fail the first read through the chain */
    backing_be.read = fake_read;
    backing_be.write = 0;
    backing_be.ctx = &backing_file;
    backing_be.total_sectors = sizeof(backing_file.bytes) / 512u;

    build_image();
    g_file_be.read = fake_read;
    g_file_be.write = fake_write;
    g_file_be.ctx = &g_file;
    g_file_be.total_sectors = FILE_BYTES / 512u;
    CHECK_INT("init with a backing image", 0,
              hype_qcow2_init(&g_q, &g_be, &g_file_be, &backing_be));
    /* A chain read that fails must refuse -- returning zeros would silently substitute
     * an empty disk for the one the chain holds. */
    CHECK_INT("backing read failure refuses", -1, hype_blk_backend_read(&g_be, 0, 1, buf));
}

static void test_l2_entry_with_flags_but_no_offset(void) {
    /* COPIED set, offset zero. Not something qemu writes, but an image can contain it,
     * and treating a zero offset as a real cluster would read the HEADER as guest data. */
    uint8_t out[512];
    unsigned int i, nonzero = 0;
    uint64_t off = 0x55u;

    build_image();
    put64(&g_file.bytes[L1_CLUSTER * CSZ], ((uint64_t)FIRST_FREE * CSZ) | (1ULL << 63));
    put64(&g_file.bytes[(uint64_t)FIRST_FREE * CSZ], 1ULL << 63); /* COPIED, offset 0 */
    CHECK_INT("init", 0, open_image());
    CHECK_INT("zero offset reads as unallocated", 0, hype_qcow2_map(&g_q, 0, &off));
    CHECK_INT("output untouched", 0x55, (long long)off);
    CHECK_INT("read succeeds", 0, hype_blk_backend_read(&g_be, 0, 1, out));
    for (i = 0; i < 512u; i++) {
        if (out[i] != 0u) {
            nonzero++;
        }
    }
    CHECK_INT("and yields zeros, not the header", 0, (long long)nonzero);
}

int main(void) {
    test_init_reports_virtual_geometry();
    test_unallocated_reads_as_zeros();
    test_write_allocates_l2_and_data_then_reads_back();
    test_second_write_in_same_cluster_reuses_it();
    test_partial_cluster_write_zeroes_the_rest();
    test_write_spanning_a_cluster_boundary();
    test_write_in_second_l1_entry();
    test_zero_flagged_cluster_reads_as_zeros();
    test_compressed_cluster_is_refused();
    test_shared_cluster_write_is_refused();
    test_shared_l2_table_write_is_refused();
    test_image_full_is_refused_not_written_outside();
    test_backing_read_through_and_copy_on_write();
    test_header_refusals();
    test_readonly_file_yields_readonly_backend();
    test_init_argument_and_io_failures();
    test_reopen_sees_previous_allocations();
    test_v2_image_without_v3_fields();
    test_second_refcount_block_is_created();
    test_refcount_table_too_small_is_refused();
    test_io_failures_surface_during_refcount_block_creation();
    test_cursor_never_hands_out_the_metadata_clusters();
    test_refcount_table_after_the_l1_table();
    test_map_past_the_l1_table();
    test_every_io_failure_surfaces();
    test_read_failures_after_init_surface();
    test_backing_read_failure_surfaces();
    test_l2_entry_with_flags_but_no_offset();

    if (failures == 0) {
        printf("all tests passed\n");
        return 0;
    }
    printf("%d test(s) failed\n", failures);
    return 1;
}
