#!/bin/bash
# M4-6b2: compile devices/dsdt.asl with iasl and emit devices/dsdt_aml.h --
# the AML *body* (everything after the 36-byte ACPI SDT header iasl produces)
# as a C byte array. hype fills its own DSDT SDT header at runtime and the
# fw_cfg table-loader recomputes the checksum, so only the body is embedded.
# Run this after editing devices/dsdt.asl; commit the regenerated header.
set -eu
cd "$(dirname "$0")/.."
ASL=devices/dsdt.asl
HDR=devices/dsdt_aml.h
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

iasl -p "$TMP/dsdt" "$ASL" >/dev/null
AML="$TMP/dsdt.aml"
TOTAL=$(stat -c%s "$AML")
BODY=$((TOTAL - 36)) # strip the 36-byte SDT header

{
    echo "#ifndef HYPE_DEVICES_DSDT_AML_H"
    echo "#define HYPE_DEVICES_DSDT_AML_H"
    echo ""
    echo "/* AUTO-GENERATED by tools/gen-dsdt-aml.sh from devices/dsdt.asl -- do not edit."
    echo " * The AML *body* of the guest DSDT (after the 36-byte SDT header); hype"
    echo " * builds the header itself and the fw_cfg table-loader recomputes the checksum. */"
    echo ""
    echo "#include <stdint.h>"
    echo ""
    echo "static const uint8_t hype_dsdt_aml_body[] = {"
    # emit the body bytes (offset 36..end) as 0xNN, 12 per line
    tail -c "$BODY" "$AML" | od -An -v -tu1 | tr -s ' ' '\n' | grep -E '^[0-9]+$' | \
        awk 'BEGIN{c=0}{printf "0x%02x, ", $1; if(++c%12==0) printf "\n    "}' | \
        sed 's/^/    /' | sed 's/    $//'
    echo ""
    echo "};"
    echo ""
    echo "#define HYPE_DSDT_AML_BODY_LEN ((uint32_t)sizeof(hype_dsdt_aml_body))"
    echo ""
    echo "#endif /* HYPE_DEVICES_DSDT_AML_H */"
} > "$HDR"

echo "gen-dsdt-aml.sh: wrote $HDR ($BODY body bytes from $TOTAL total AML)"
