#!/bin/bash
# #536: run micro-kernel guests under QEMU and report their verdicts.
#
#   tools/micro/run-micro.sh [name ...]        one VM per named test, sequentially
#   tools/micro/run-micro.sh --suite <cfg>     one run, all VMs in that config
#
# With no arguments, runs every artifact `make micro` builds.
#
# WHAT COUNTS AS A FAILURE, and why the list is longer than it looks:
#
#   MICRO FAIL          the test said so.
#   no verdict at all   the test wedged, triple-faulted before reporting, or was never entered.
#   PANIC               hype itself died; no verdict on this run can be trusted.
#   no hype banner      the boot never reached hype (#371: roughly one QEMU boot in four leaves a
#                       113-byte log that reads exactly like a guest wedge). Reported as NOBOOT,
#                       which is distinct from a failure -- scoring it as either would be a lie.
#
# The third and fourth exist because SILENCE IS THE FAILURE MODE THAT LOOKS MOST LIKE SUCCESS, and
# it is the one that actually happened: #535's first run reported a correct PASS from a guest
# entered at the wrong address entirely. A harness that greps only for FAIL passes a dead test.
set -u
cd "$(dirname "$0")/../.."

SECS="${SECS:-90}"
ISO="${MICRO_ISO:-/usr/share/edk2/ovmf/UefiShell.iso}"
MEM_MB="${MICRO_MEM_MB:-512}"
OUTDIR=disk-images

[ -f build/hype.efi ] || { echo "build/hype.efi missing -- run 'make all'"; exit 2; }
[ -f "$ISO" ] || { echo "no ISO at $ISO -- set MICRO_ISO=<path>"; exit 2; }

# The rig needs an ISO argument even for a kernel VM, which attaches no media. Any small ISO does;
# it is never read by these guests.

gen_cfg() {   # $1 = test name, $2 = output path
    cat > "$2" <<CFG
; generated by tools/micro/run-micro.sh -- edit tests/micro/suite-*.cfg instead
[hype]
config_version = 1
log_level = debug

[vm.$1]
label = micro/$1
vcpus = 1
mem_mb = $MEM_MB
boot = kernel
kernel = \\EFI\\hype\\micro\\$1.bin
os_hint = none
CFG
}

# Reports one VM's verdict from a finished log. Echoes a status word and returns non-zero on
# anything that is not a pass.
verdict_of() {   # $1 = log, $2 = test name
    local log="$1" name="$2"
    if LC_ALL=C grep -aq "MICRO FAIL: $name" "$log"; then
        echo "FAIL   $name -- $(LC_ALL=C grep -a -m1 "MICRO FAIL: $name" "$log" | sed 's/.*MICRO FAIL: //')"
        return 1
    fi
    if LC_ALL=C grep -aq "MICRO PASS: $name" "$log"; then
        echo "PASS   $name"
        return 0
    fi
    echo "NOVERDICT $name -- no MICRO PASS or MICRO FAIL line; the guest never reported"
    return 1
}

run_one() {   # $1 = test name
    local name="$1" cfg log
    cfg="$OUTDIR/micro-$name.cfg"
    log="$OUTDIR/run-micro-$name.log"
    [ -f "build/micro/$name.bin" ] || { echo "MISSING $name -- build/micro/$name.bin, run 'make micro'"; return 1; }
    gen_cfg "$name" "$cfg"

    killall -9 qemu-system-x86_64 2>/dev/null
    sleep 1
    HYPE_CFG="$cfg" HYPE_KERNELS="build/micro/$name.bin" \
        timeout $((SECS + 150)) tools/run-guest.sh "$ISO" "micro-$name" "$SECS" >/dev/null 2>&1

    report "$log" "$name"
}

report() {   # $1 = log, $2.. = test names present in it
    local log="$1"; shift
    local rc=0 n
    if [ ! -s "$log" ]; then
        echo "NOBOOT ($*) -- no log at all"
        return 2
    fi
    if ! LC_ALL=C grep -aq "hype: build" "$log"; then
        # #371: not a failure, and must not be scored as one.
        echo "NOBOOT ($*) -- the boot never reached hype ($(wc -c <"$log") byte log); re-run"
        return 2
    fi
    if LC_ALL=C grep -aq "PANIC" "$log"; then
        echo "PANIC  ($*) -- hype died, so no verdict on this run means anything:"
        LC_ALL=C grep -a -m1 "PANIC" "$log" | sed 's/^/         /'
        return 1
    fi
    for n in "$@"; do
        verdict_of "$log" "$n" || rc=1
    done
    return $rc
}

# --suite <cfg>: one run, every VM in that config. The names are taken from its [vm.<name>]
# headers, so the config stays the single statement of what the suite is.
if [ "${1:-}" = "--suite" ]; then
    cfg="${2:-}"
    [ -n "$cfg" ] && [ -f "$cfg" ] || { echo "usage: $0 --suite <hype.cfg>"; exit 2; }
    names=$(sed -n 's/^\[vm\.\([A-Za-z0-9_-]*\)\].*/\1/p' "$cfg")
    [ -n "$names" ] || { echo "no [vm.*] sections in $cfg"; exit 2; }
    kernels=""
    for n in $names; do
        [ -f "build/micro/$n.bin" ] || { echo "MISSING $n -- build/micro/$n.bin, run 'make micro'"; exit 1; }
        kernels="$kernels build/micro/$n.bin"
    done
    tag="suite-$(basename "$cfg" .cfg)"
    killall -9 qemu-system-x86_64 2>/dev/null
    sleep 1
    HYPE_CFG="$cfg" HYPE_KERNELS="$kernels" \
        timeout $((SECS + 180)) tools/run-guest.sh "$ISO" "$tag" "$SECS" >/dev/null 2>&1
    # shellcheck disable=SC2086
    report "$OUTDIR/run-$tag.log" $names
    exit $?
fi

# Default: every artifact the Makefile knows about, minus the ones excluded below.
#
# EXCLUSIONS ARE NAMED WITH A REASON, and there are only two kinds:
#
#   faulter  exists to fail (#538). Including it would make a healthy run look broken.
#   pflash   FAILS TODAY on a real hype defect, #556: a guest CFI read after a command returns
#            array data instead of the synthesized response. The test is correct and its failure is
#            the bug report -- run it explicitly with `run-micro.sh pflash` to see it. It is excluded
#            so the default run stays a signal, and this line is deleted when #556 is fixed.
#
# A silent exclusion would be worse than a failing default: it would make the suite claim coverage it
# does not have. Both are printed, so a run says what it did not do.
MICRO_EXCLUDE_DEFAULT="faulter pflash"

if [ $# -eq 0 ]; then
    all=$(sed -n 's/^MICRO_NAMES := //p' Makefile | tr ' ' '\n' | grep -v '^$')
    set --
    for _n in $all; do
        _skip=0
        for _x in $MICRO_EXCLUDE_DEFAULT; do
            [ "$_n" = "$_x" ] && _skip=1
        done
        if [ "$_skip" = "1" ]; then
            echo "SKIP   $_n -- excluded from the default run on purpose; see MICRO_EXCLUDE_DEFAULT"
        else
            set -- "$@" "$_n"
        fi
    done
fi

rc=0
for t in "$@"; do
    run_one "$t" || rc=1
done
exit $rc
