#!/bin/bash
# #536: run micro-kernel guests under QEMU and report their verdicts.
#
#   tools/micro/run-micro.sh [name ...]        one VM per named test, sequentially
#   tools/micro/run-micro.sh --suite <cfg>     one run, all VMs in that config
#
# With no arguments, runs every artifact `make micro` builds.
#
# WHAT COUNTS AS A FAILURE, and why the list is longer than it looks:
#
#   MICRO FAIL          the test said so.
#   no verdict at all   the test wedged, triple-faulted before reporting, or was never entered.
#   PANIC               hype itself died; no verdict on this run can be trusted.
#   no hype banner      the boot never reached hype (#371: roughly one QEMU boot in four leaves a
#                       113-byte log that reads exactly like a guest wedge). Reported as NOBOOT,
#                       which is distinct from a failure -- scoring it as either would be a lie.
#
# The third and fourth exist because SILENCE IS THE FAILURE MODE THAT LOOKS MOST LIKE SUCCESS, and
# it is the one that actually happened: #535's first run reported a correct PASS from a guest
# entered at the wrong address entirely. A harness that greps only for FAIL passes a dead test.
set -u
cd "$(dirname "$0")/../.."

SECS="${SECS:-90}"
ISO="${MICRO_ISO:-/usr/share/edk2/ovmf/UefiShell.iso}"
MEM_MB="${MICRO_MEM_MB:-512}"
OUTDIR=disk-images

[ -f build/hype.efi ] || { echo "build/hype.efi missing -- run 'make all'"; exit 2; }
[ -f "$ISO" ] || { echo "no ISO at $ISO -- set MICRO_ISO=<path>"; exit 2; }

# The rig needs an ISO argument even for a kernel VM, which attaches no media. Any small ISO does;
# it is never read by these guests.

# #83: which tests need a REAL uplink. They get hype's own address in [hype] and a QEMU e1000 on
# user networking (see NET_QEMU_ARGS), because a NAT test with no host NIC tests nothing -- and the
# rig's default `-nodefaults` gives hype no network device at all, which is why #80's own log line
# reads "no Ethernet controller found".
#
# 10.0.2.15 / 10.0.2.2 are QEMU user-mode networking's fixed layout, not a guess: slirp always hands
# out .15 first and is itself the gateway at .2. Hardcoded HERE, in the harness that creates that
# network, rather than in hype -- which takes its address from config precisely so it is not
# assuming a QEMU-shaped world.
needs_uplink() {
    case "$1" in
        netdns|netgoal|e1000dns) return 0 ;;
        *) return 1 ;;
    esac
}
NET_QEMU_ARGS="-netdev user,id=hnet0 -device e1000,netdev=hnet0"

gen_cfg() {   # $1 = test name, $2 = output path
    cat > "$2" <<CFG
; generated by tools/micro/run-micro.sh -- edit tests/micro/suite-*.cfg instead
[hype]
config_version = 1
log_level = debug
CFG
    if needs_uplink "$1"; then
        cat >> "$2" <<CFG
uplink_ip = 10.0.2.15
uplink_mask = 255.255.255.0
uplink_gateway = 10.0.2.2
CFG
    fi
    cat >> "$2" <<CFG

[vm.$1]
label = micro/$1
vcpus = 1
mem_mb = $MEM_MB
boot = kernel
kernel = \\EFI\\hype\\micro\\$1.bin
CFG
    # os_hint is emitted ONCE, here, because it selects the NIC frontend (#82) and a duplicate key is
    # a parse error -- correctly so. Appending a second `os_hint` to a base that already had one made
    # hype refuse the whole config ("parse error status=4 line=17") and the guest booted with no
    # config at all, which presented as a test that produced no output whatsoever.
    case "$1" in
        e1000dns) printf 'os_hint = windows\n' >> "$2" ;;
        *) printf 'os_hint = none\n' >> "$2" ;;
    esac
    cat >> "$2" <<CFG
CFG
    # #550: a storage test needs a REAL backing file, or it is testing its own scaffolding.
    # The disk is declared here rather than in the test so the same artifact can be aimed at a
    # raw image, a qcow2 (#336) or a thin target (decision 42) by editing a config.
    # #565: the VBE adapter exists only when a config asks for it (decision 49).
    case "$1" in
        bochsvbe) printf 'display = bochs\n' >> "$2" ;;
    esac
    # #81: the virtio-net adapter exists only when the VM asks for a network (plan.md 6e's default
    # is `none`, so a test that needs a NIC has to say so, exactly as bochsvbe does for a display).
    case "$1" in
        virtionet|netdns|netgoal|netpeer|e1000dns) printf 'net_mode = nat\n' >> "$2" ;;
    esac
    case "$1" in
        virtioblk|atadisk|ahci) cat >> "$2" <<CFG
disks = d0

[disk.d0]
type = disk
backing = file
path = \\hype\\disks\\$1.img
bus = $(case "$1" in virtioblk) echo virtio-blk ;; *) echo ahci-sata ;; esac)
CFG
        ;;
    esac
}

# The host half of a storage test's verdict (#343's re-read-and-compare). A read that returns what
# was written proves the round trip through the DEVICE; it does not prove the bytes reached the
# FILE, because a device serving from its own cache would pass identically. Only the host can tell
# those apart, so this pulls the image back out of the ESP and checks the sector itself.
verify_backing_file() {   # $1 = test name, $2 = sector
    local name="$1" sector="${2:-1}" img="$OUTDIR/$name.verify.img" esp="$OUTDIR/run-micro-$name.esp.img"
    [ -f "$esp" ] || { echo "       (no ESP image to verify against)"; return 1; }
    rm -f "$img"
    if ! mcopy -i "$esp@@1M" "::/hype/disks/$name.img" "$img" 2>/dev/null; then
        echo "       HOST-SIDE VERIFY FAILED: could not read the backing image back out of the ESP"
        return 1
    fi
    python3 - "$img" "$sector" "$name" <<'PY'
import sys
path, sector, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
with open(path, 'rb') as f:
    f.seek(sector * 512)
    got = f.read(512)
if len(got) != 512:
    print("       HOST-SIDE VERIFY FAILED: image is shorter than sector %d" % sector)
    sys.exit(1)
want = bytes(((0x5A ^ i ^ (sector & 0xFF)) & 0xFF) for i in range(512))
if got != want:
    first = next(i for i in range(512) if got[i] != want[i])
    print("       HOST-SIDE VERIFY FAILED: sector %d byte %d is 0x%02x, expected 0x%02x" %
          (sector, first, got[first], want[first]))
    if got == bytes(512):
        print("       the sector is all zeros -- the guest's write never reached the file")
    sys.exit(1)
print("       host-side verify: sector %d in the backing FILE matches the guest's pattern" % sector)
PY
}

# Reports one VM's verdict from a finished log. Echoes a status word and returns non-zero on
# anything that is not a pass.
verdict_of() {   # $1 = log, $2 = test name
    local log="$1" name="$2"
    if LC_ALL=C grep -aq "MICRO FAIL: $name" "$log"; then
        echo "FAIL   $name -- $(LC_ALL=C grep -a -m1 "MICRO FAIL: $name" "$log" | sed 's/.*MICRO FAIL: //')"
        return 1
    fi
    if LC_ALL=C grep -aq "MICRO PASS: $name" "$log"; then
        # SOME TESTS HAVE A HOST-SIDE HALF, and a guest-only pass would be a test that cannot
        # fail for the reason that matters. The guest can prove it owns the framebuffer it
        # announced; only hype can say the config was accepted (#549). Same split the
        # PAUSE-filter test settled (#540).
        if [ "$name" = ramfb ]; then
            if ! LC_ALL=C grep -aq "RAMFB vm[0-9]*: decoded " "$log"; then
                echo "FAIL   $name -- the guest passed but hype never decoded a ramfb config;" \
                     "the guest half alone does not prove the transport"
                return 1
            fi
            local blits
            blits=$(LC_ALL=C grep -ao "blits=[0-9]*" "$log" | tail -1 | cut -d= -f2)
            echo "PASS   $name (hype decoded the config; blits=${blits:-0} -- 0 only means this VM"\
                 "was not the on-screen view)"
            return 0
        fi
        echo "PASS   $name"
        return 0
    fi
    echo "NOVERDICT $name -- no MICRO PASS or MICRO FAIL line; the guest never reported"
    return 1
}

run_one() {   # $1 = test name
    local name="$1" cfg log
    cfg="$OUTDIR/micro-$name.cfg"
    log="$OUTDIR/run-micro-$name.log"
    [ -f "build/micro/$name.bin" ] || { echo "MISSING $name -- build/micro/$name.bin, run 'make micro'"; return 1; }
    gen_cfg "$name" "$cfg"

    killall -9 qemu-system-x86_64 2>/dev/null
    sleep 1

    # A storage test gets a freshly zeroed image, so a pattern found afterwards can only have been
    # written by this run -- a leftover from the previous one would pass without the guest doing
    # anything.
    local disk=""
    case "$name" in
        virtioblk|atadisk|ahci)
            disk="$OUTDIR/$name.img"
            rm -f "$disk"
            dd if=/dev/zero of="$disk" bs=1M count=1 status=none
            ;;
    esac

    # A test that needs input from OUTSIDE the guest declares it by having a script at
    # tests/micro/input/<name>.txt, and the runner stages it at \input\vm0.txt. Derived from the
    # file's existence rather than a name list, so a new test gets input by adding a file.
    #
    # This was missing, and its absence was invisible in the worst way: ps2 could not pass in the
    # default run at all, because its script existed in the repo and was never shipped. The test
    # said out loud that it needed one; nothing carried it across.
    local inputs=""
    if [ -f "tests/micro/input/$name.txt" ]; then
        inputs="tests/micro/input/$name.txt"
    fi

    local qargs="${EXTRA_QEMU_ARGS:-}"
    if needs_uplink "$name"; then
        qargs="$qargs $NET_QEMU_ARGS"
    fi

    HYPE_CFG="$cfg" HYPE_KERNELS="build/micro/$name.bin" HYPE_DISK="$disk" HYPE_INPUTS="$inputs" \
        EXTRA_QEMU_ARGS="$qargs" \
        timeout $((SECS + 150)) tools/run-guest.sh "$ISO" "micro-$name" "$SECS" >/dev/null 2>&1

    report "$log" "$name" || return 1
    # Only the tests that WRITE data get the host-side pattern check. ahci issues IDENTIFY, which
    # transfers device metadata and touches no sector -- demanding a pattern there would fail a
    # correct run.
    case "$name" in
        virtioblk|atadisk) verify_backing_file "$name" 1 || return 1 ;;
    esac
}

report() {   # $1 = log, $2.. = test names present in it
    local log="$1"; shift
    local rc=0 n
    if [ ! -s "$log" ]; then
        echo "NOBOOT ($*) -- no log at all"
        return 2
    fi
    if ! LC_ALL=C grep -aq "hype: build" "$log"; then
        # #371: not a failure, and must not be scored as one.
        echo "NOBOOT ($*) -- the boot never reached hype ($(wc -c <"$log") byte log); re-run"
        return 2
    fi
    if LC_ALL=C grep -aq "PANIC" "$log"; then
        echo "PANIC  ($*) -- hype died, so no verdict on this run means anything:"
        LC_ALL=C grep -a -m1 "PANIC" "$log" | sed 's/^/         /'
        return 1
    fi
    for n in "$@"; do
        verdict_of "$log" "$n" || rc=1
    done
    return $rc
}

# --suite <cfg>: one run, every VM in that config. The names are taken from its [vm.<name>]
# headers, so the config stays the single statement of what the suite is.
if [ "${1:-}" = "--suite" ]; then
    cfg="${2:-}"
    [ -n "$cfg" ] && [ -f "$cfg" ] || { echo "usage: $0 --suite <hype.cfg>"; exit 2; }
    names=$(sed -n 's/^\[vm\.\([A-Za-z0-9_-]*\)\].*/\1/p' "$cfg")
    [ -n "$names" ] || { echo "no [vm.*] sections in $cfg"; exit 2; }
    # WHICH BINARY each VM wants comes from its own `kernel =` line, not from the section name.
    # Those coincide for a one-test-per-VM suite and do not in general: suite-peers.cfg runs the SAME
    # netpeer binary as two VMs named `a` and `b`, told apart by their cmdline. Deriving the path
    # from the section name made that config unstageable ("MISSING a"), and the config was right --
    # it already says what it wants to boot.
    #
    # Deduplicated, because staging one file twice under the same name is harmless but staging it
    # twice makes the MISSING check fire on the second pass for no reason.
    kernels=""
    for k in $(sed -n 's#^[[:space:]]*kernel[[:space:]]*=[[:space:]]*.*\\\([A-Za-z0-9_-]*\.bin\)[[:space:]]*$#\1#p' "$cfg" | sort -u); do
        [ -f "build/micro/$k" ] || { echo "MISSING build/micro/$k -- run 'make micro'"; exit 1; }
        kernels="$kernels build/micro/$k"
    done
    [ -n "$kernels" ] || { echo "no `kernel =` lines in $cfg -- nothing to stage"; exit 2; }
    tag="suite-$(basename "$cfg" .cfg)"
    # HYPE_INPUTS is POSITIONAL -- the first path becomes \input\vm0.txt, the second vm1.txt. So a
    # VM with no script of its own still needs a slot, or every VM after it is handed the wrong
    # script. An empty placeholder holds the position; the tests that read no input cannot tell an
    # empty script from an absent one, and the ones that do read input get theirs.
    inputs=""
    have_input=0
    : > "$OUTDIR/micro-noinput.txt"
    for n in $names; do
        if [ -f "tests/micro/input/$n.txt" ]; then
            inputs="$inputs tests/micro/input/$n.txt"
            have_input=1
        else
            inputs="$inputs $OUTDIR/micro-noinput.txt"
        fi
    done
    [ "$have_input" = "1" ] || inputs=""
    # A suite gets the host NIC if ANY of its VMs boots a test that needs one, and also if the
    # config itself carries uplink keys -- a config asking for an uplink and a rig that gives it no
    # NIC is the combination that produced a whole run of `no_uplink` drops.
    suite_qargs="${EXTRA_QEMU_ARGS:-}"
    if grep -q '^[[:space:]]*uplink_ip[[:space:]]*=' "$cfg" 2>/dev/null; then
        suite_qargs="$suite_qargs $NET_QEMU_ARGS"
    else
        for k in $(printf '%s\n' $kernels | sed 's#.*/##; s#\.bin$##'); do
            if needs_uplink "$k"; then
                suite_qargs="$suite_qargs $NET_QEMU_ARGS"
                break
            fi
        done
    fi

    killall -9 qemu-system-x86_64 2>/dev/null
    sleep 1
    HYPE_CFG="$cfg" HYPE_KERNELS="$kernels" HYPE_INPUTS="$inputs" EXTRA_QEMU_ARGS="$suite_qargs" \
        timeout $((SECS + 180)) tools/run-guest.sh "$ISO" "$tag" "$SECS" >/dev/null 2>&1
    # A VERDICT PER VM, matched on the TEST each VM boots rather than on the VM's own name.
    #
    # A microtest prints `MICRO PASS: <its own NAME>` -- the binary's name, not the config section's.
    # Those coincide for one-test-per-VM suites and do not when two VMs run one binary:
    # suite-peers.cfg boots netpeer as `a` and `b`, both guests passed, and the runner reported
    # NOVERDICT for both because it was grepping for "MICRO PASS: a".
    #
    # COUNTING is what makes this a real check rather than a grep. Two VMs running netpeer must
    # produce TWO netpeer verdicts: one guest passing while the other never reported is exactly the
    # half-working forwarding this suite exists to catch, and a plain match would call that a pass.
    suite_rc=0
    for k in $(printf '%s\n' $kernels | sed 's#.*/##; s#\.bin$##' | sort -u); do
        want=0
        for vm in $names; do
            vmk=$(sed -n "/^\[vm\.$vm\]/,/^\[vm\./p" "$cfg" |
                  sed -n 's#^[[:space:]]*kernel[[:space:]]*=[[:space:]]*.*\\\([A-Za-z0-9_-]*\)\.bin[[:space:]]*$#\1#p' |
                  head -1)
            [ "$vmk" = "$k" ] && want=$((want + 1))
        done
        [ "$want" -gt 0 ] || want=1
        # DISTINCT VMs that reported, not matching lines. hype writes each guest record to more
        # than one sink -- once with a `ttyS0|` prefix and again with `screen|`, sometimes twice --
        # so a raw count said "6 of 2 VM(s) reported". Pulling the vmN out of the prefix and
        # deduplicating asks the question that was meant: HOW MANY VMs said this. It also stays
        # right on a rig with no serial sink, where only the screen records exist.
        passes=$(LC_ALL=C grep -ao "vm[0-9]\+ [A-Za-z0-9]*| MICRO PASS: $k" "$OUTDIR/run-$tag.log" 2>/dev/null |
                 sed 's/^\(vm[0-9]*\).*/\1/' | sort -u | grep -c . || true)
        fails=$(LC_ALL=C grep -ao "vm[0-9]\+ [A-Za-z0-9]*| MICRO FAIL: $k" "$OUTDIR/run-$tag.log" 2>/dev/null |
                sed 's/^\(vm[0-9]*\).*/\1/' | sort -u | grep -c . || true)
        passes=${passes:-0}
        fails=${fails:-0}
        if [ "$fails" -gt 0 ]; then
            echo "FAIL   $k -- $(LC_ALL=C grep -a -m1 "MICRO FAIL: $k" "$OUTDIR/run-$tag.log" | sed 's/.*MICRO FAIL: //')"
            suite_rc=1
        elif [ "$passes" -ge "$want" ]; then
            echo "PASS   $k ($passes of $want VM(s) reported)"
        else
            echo "NOVERDICT $k -- $passes of $want VM(s) running it reported; the rest never did"
            suite_rc=1
        fi
    done
    exit $suite_rc
fi

# Default: every artifact the Makefile knows about, minus the ones excluded below.
#
# EXCLUSIONS ARE NAMED WITH A REASON, and there are only two kinds:
#
#   faulter  exists to fail (#538). Including it would make a healthy run look broken.
#
# A silent exclusion would be worse than a failing default: it would make the suite claim coverage it
# does not have. Every exclusion is printed, so a run says what it did not do.
#
# pflash used to be listed here for #556 -- "a guest CFI read after a command returns array data".
# There was no such defect: the model returns 0 because hype_pflash_reset() clears the status
# register, which OVMF's probe depends on, and the test was asserting the wrong thing. pflash is
# in the default run and passes. Recorded rather than deleted because an exclusion citing a defect
# that does not exist removes real coverage for as long as nobody rechecks it.
#   netpeer  needs TWO VMs to have anything to talk to, and a `self=`/`peer=` cmdline the per-test
#            path does not generate. Run it as a suite: `--suite tests/micro/suite-peers.cfg`, and
#            `suite-peers-denied.cfg` for the isolation case whose healthy result is a failure.
#   netgoal  the same, and it is the whole-goal config: two VMs each pinging www.google.com and each
#            other. `--suite tests/micro/suite-goal.cfg`.
#
# Both are EXCLUDED RATHER THAN LEFT TO FAIL, because a test that cannot pass in the default run is
# noise that trains a reader to ignore the run -- and they are named here with how to run them, so
# the exclusion does not hide them either.
MICRO_EXCLUDE_DEFAULT="faulter netpeer netgoal"

if [ $# -eq 0 ]; then
    all=$(sed -n 's/^MICRO_NAMES := //p' Makefile | tr ' ' '\n' | grep -v '^$')
    set --
    for _n in $all; do
        _skip=0
        for _x in $MICRO_EXCLUDE_DEFAULT; do
            [ "$_n" = "$_x" ] && _skip=1
        done
        if [ "$_skip" = "1" ]; then
            echo "SKIP   $_n -- excluded from the default run on purpose; see MICRO_EXCLUDE_DEFAULT"
        else
            set -- "$@" "$_n"
        fi
    done
fi

rc=0
for t in "$@"; do
    run_one "$t" || rc=1
done
exit $rc
